'use client';

import styles from '../privacidade/page.module.css';
import { useLanguage } from '@/lib/i18n/LanguageContext';

const content = {
  pt: {
    title: 'Aviso Legal e Termos de Uso',
    updated: 'Última atualização: 22 de junho de 2026',
    sections: [
      { title: '1. Natureza das Informações', body: 'As informações disponibilizadas pela Make It Easy USA, seja em nosso site, redes sociais, materiais promocionais, e-mails, webinars, orientações ou qualquer outro canal de comunicação, possuem caráter exclusivamente informativo e educacional. Tais informações não devem, sob nenhuma hipótese, ser interpretadas como aconselhamento jurídico, imigratório, financeiro ou tributário.' },
      { title: '2. Ausência de Representação Jurídica', body: 'A Make It Easy USA não é um escritório de advocacia, não emprega advogados licenciados nos Estados Unidos em capacidade de representação legal, e não presta consultoria jurídica de qualquer natureza. Não atuamos como representantes credenciados perante o USCIS (United States Citizenship and Immigration Services), o Departamento de Estado dos EUA, embaixadas, consulados, SEVP (Student and Exchange Visitor Program), ou qualquer outro órgão governamental americano ou estrangeiro.', bodyAfter: 'Recomendamos enfaticamente que estudantes e candidatos consultem um advogado de imigração devidamente licenciado nos Estados Unidos antes de tomar decisões relacionadas a vistos, status migratório, CPT, OPT, mudança de status, ou qualquer outro benefício imigratório.' },
      { title: '3. Sobre o CPT (Curricular Practical Training)', body: 'A autorização de CPT é determinada exclusivamente pela universidade, por meio do Designated School Official (DSO), de acordo com as políticas institucionais aplicáveis e com os regulamentos federais vigentes (8 CFR 214.2(f)(10)(i)).', bodyAfter: 'O CPT é, por definição regulamentar, parte integrante do currículo acadêmico e deve estar diretamente relacionado ao programa de estudos do estudante. A Make It Easy USA não autoriza, processa, aprova ou influencia decisões de CPT.' },
      { title: '4. Sobre o OPT (Optional Practical Training)', body: 'A autorização de OPT é analisada e concedida exclusivamente pelo USCIS. A Make It Easy USA não tem qualquer ingerência sobre prazos de processamento, aprovações, negativas ou requisições de evidência adicional emitidas pelo USCIS.' },
      { title: '5. Finalidade Acadêmica dos Programas', body: 'Os programas de mestrado e demais cursos para os quais a Make It Easy USA realiza recrutamento e divulgação possuem finalidade exclusivamente acadêmica e educacional. O principal objetivo dos programas é o estudo, a formação acadêmica e o desenvolvimento profissional do estudante.', bodyAfter: 'Estes programas não devem ser interpretados, utilizados ou contratados como meio primário de obtenção de autorização de trabalho nos Estados Unidos ou de benefícios imigratórios. Candidatos cuja intenção principal não seja acadêmica não devem se inscrever, pois isso pode configurar violação do status F-1 e resultar em consequências imigratórias graves, incluindo perda de status, e impedimento de reentrada nos Estados Unidos.' },
      { title: '6. Ausência de Garantias', body: 'A Make It Easy USA não garante, expressa ou implicitamente:', list: ['Aprovação de admissão acadêmica em qualquer instituição', 'Concessão de visto F-1, F-2, ou qualquer outra categoria de visto', 'Autorização de CPT ou OPT', 'Aprovação de transferência entre instituições', 'Aprovação de mudança de status imigratório', 'Obtenção de emprego, estágio ou oportunidade profissional nos Estados Unidos', 'Renovação de visto ou extensão de status', 'Qualquer outro benefício imigratório, acadêmico ou profissional'], bodyAfter: 'Todas as decisões finais cabem às instituições de ensino, ao USCIS, ao Departamento de Estado, aos oficiais consulares e a outros órgãos competentes.' },
      { title: '7. Decisões Consulares', body: 'A concessão do visto F-1 é decisão exclusiva e discricionária do oficial consular no momento da entrevista no consulado ou embaixada americana. A Make It Easy USA não tem qualquer influência sobre essa decisão e não pode prever ou garantir seu resultado.' },
      { title: '8. Responsabilidades do Estudante', body: 'Cada estudante é individual e integralmente responsável por:', list: ['Verificar sua elegibilidade acadêmica, financeira e imigratória junto às instituições competentes', 'Manter seu status F-1 ativo, cumprindo todos os requisitos de matrícula, frequência, desempenho acadêmico e demais obrigações estabelecidas pela universidade e pela legislação imigratória americana', 'Prestar informações verdadeiras, completas e precisas em todas as etapas do processo (admissão, visto, manutenção de status)', 'Cumprir os termos e condições do CPT/OPT conforme autorizados', 'Buscar orientação de profissionais devidamente licenciados (advogados de imigração, contadores, consultores financeiros) quando necessário', 'Acompanhar mudanças nas leis e regulamentações imigratórias americanas, que podem ocorrer a qualquer momento'] },
      { title: '9. Modelo de Atuação e Gratuidade dos Serviços ao Estudante', body: 'A Make It Easy USA atua como agente de recrutamento internacional, e nosso trabalho é financiado pelas universidades parceiras por meio de acordos comerciais firmados diretamente entre a empresa e cada instituição.', bodyAfter: 'Atualmente, os serviços de orientação, informação, encaminhamento e acompanhamento prestados aos estudantes e candidatos são integralmente gratuitos. A Make It Easy USA não cobra do estudante taxas de inscrição, taxas de aplicação, taxas de acompanhamento, mensalidades, comissões ou qualquer outro valor pelos serviços de recrutamento e orientação que presta.<br/><br/>Não existe relação contratual direta entre a Make It Easy USA e o estudante. O estudante é beneficiário dos serviços de orientação oferecidos pela empresa, no contexto de seu interesse em ingressar em programas acadêmicos das universidades parceiras.<br/><br/>A Make It Easy USA reserva-se o direito de, no futuro, oferecer serviços complementares opcionais mediante pagamento (como consultorias avulsas, mentorias ou produtos educacionais). Caso isso venha a ocorrer, tais serviços serão sempre claramente identificados como pagos e opcionais, com valores, condições e escopo informados de forma transparente e prévia ao estudante, jamais sendo condição para acesso aos serviços gratuitos de recrutamento aqui descritos.<br/><br/>Qualquer cobrança realizada em nome da Make It Easy USA fora dos termos aqui descritos deve ser imediatamente reportada ao e-mail info@makeiteasyusa.com, pois pode configurar tentativa de fraude.' },
      { title: '10. Pagamentos a Terceiros', body: 'Valores pagos pelo estudante a universidades, taxas SEVIS (I-901), taxas consulares (MRV), taxas do USCIS, despesas com tradução juramentada, exames de proficiência, passagens aéreas, seguros, hospedagem e demais despesas relacionadas ao processo são de responsabilidade exclusiva do estudante e não são reembolsáveis pela Make It Easy USA, independentemente do resultado de admissão, visto ou status.', bodyAfter: 'A Make It Easy USA não intermedia, recebe, processa ou tem qualquer ingerência sobre esses pagamentos a terceiros.' },
      { title: '11. Alterações Regulamentares', body: 'As leis e regulamentos imigratórios dos Estados Unidos podem sofrer alterações a qualquer momento, sem aviso prévio. Informações que são precisas na data de publicação podem tornar-se desatualizadas. A Make It Easy USA não se responsabiliza por mudanças regulamentares supervenientes que afetem o processo, status ou benefícios do estudante.' },
      { title: '12. Limitação de Responsabilidade', body: 'Na máxima extensão permitida pela legislação aplicável, a Make It Easy USA, seus sócios, colaboradores, prepostos e parceiros não se responsabilizam por quaisquer danos diretos, indiretos, incidentais, consequenciais, lucros cessantes ou perdas decorrentes de decisões tomadas com base nas informações disponibilizadas, de negativas de visto, CPT, OPT ou admissão, de perda de status migratório, ou de qualquer outro evento relacionado ao processo do estudante.' },
      { title: '13. Aceitação dos Termos', body: 'Ao utilizar os serviços, informações, materiais ou canais de comunicação da Make It Easy USA, participar de nossos eventos ou orientações, ou se candidatar a programas acadêmicos por nosso intermédio, o estudante declara ter lido, compreendido e concordado integralmente com os termos deste Aviso Legal.', bodyAfter: 'Em caso de dúvidas sobre este Aviso Legal, entre em contato: <a href="mailto:info@makeiteasyusa.com">info@makeiteasyusa.com</a>' },
    ],
  },
  en: {
    title: 'Legal Disclaimer and Terms of Use',
    updated: 'Last updated: June 22, 2026',
    sections: [
      { title: '1. Nature of Information', body: 'The information provided by Make It Easy USA, whether on our website, social networks, promotional materials, emails, webinars, guidelines, or any other communication channel, is strictly for informational and educational purposes. Such information should not, under any circumstances, be construed as legal, immigration, financial, or tax advice.' },
      { title: '2. No Legal Representation', body: 'Make It Easy USA is not a law firm, does not employ attorneys licensed in the United States in a legal representation capacity, and does not provide legal consulting of any kind. We do not act as accredited representatives before USCIS, the US Department of State, embassies, consulates, SEVP, or any other US or foreign government agency.', bodyAfter: 'We strongly recommend that students and applicants consult a duly licensed immigration attorney in the United States before making decisions related to visas, immigration status, CPT, OPT, change of status, or any other immigration benefit.' },
      { title: '3. About CPT (Curricular Practical Training)', body: 'CPT authorization is determined exclusively by the university, through the Designated School Official (DSO), in accordance with applicable institutional policies and current federal regulations (8 CFR 214.2(f)(10)(i)).', bodyAfter: 'CPT is, by regulatory definition, an integral part of the academic curriculum and must be directly related to the student\'s program of study. Make It Easy USA does not authorize, process, approve, or influence CPT decisions.' },
      { title: '4. About OPT (Optional Practical Training)', body: 'OPT authorization is analyzed and granted exclusively by USCIS. Make It Easy USA has no involvement in processing times, approvals, denials, or requests for evidence issued by USCIS.' },
      { title: '5. Academic Purpose of Programs', body: 'The master\'s programs and other courses for which Make It Easy USA recruits and promotes have an exclusively academic and educational purpose. The main objective of the programs is the study, academic training, and professional development of the student.', bodyAfter: 'These programs should not be interpreted, used, or contracted as a primary means of obtaining work authorization in the United States or immigration benefits. Applicants whose main intention is not academic should not apply, as this may constitute a violation of F-1 status and result in serious immigration consequences, including loss of status and prevention of reentry into the United States.' },
      { title: '6. No Guarantees', body: 'Make It Easy USA does not guarantee, explicitly or implicitly:', list: ['Approval of academic admission to any institution', 'Granting of an F-1, F-2, or any other visa category', 'Authorization of CPT or OPT', 'Approval of transfer between institutions', 'Approval of change of immigration status', 'Obtaining employment, internships, or professional opportunities in the US', 'Visa renewal or extension of status', 'Any other immigration, academic, or professional benefit'], bodyAfter: 'All final decisions rest with the educational institutions, USCIS, the Department of State, consular officers, and other competent bodies.' },
      { title: '7. Consular Decisions', body: 'The granting of the F-1 visa is an exclusive and discretionary decision of the consular officer at the time of the interview at the American consulate or embassy. Make It Easy USA has no influence over this decision and cannot predict or guarantee its outcome.' },
      { title: '8. Student Responsibilities', body: 'Each student is individually and fully responsible for:', list: ['Verifying their academic, financial, and immigration eligibility with the competent institutions', 'Maintaining their active F-1 status, fulfilling all enrollment, attendance, academic performance requirements, and other obligations established by the university and American immigration law', 'Providing true, complete, and accurate information at all stages of the process', 'Complying with the terms and conditions of CPT/OPT as authorized', 'Seeking guidance from properly licensed professionals (immigration lawyers, accountants, financial advisors) when necessary', 'Keeping up with changes in US immigration laws and regulations'] },
      { title: '9. Operating Model and Free Student Services', body: 'Make It Easy USA acts as an international recruitment agent, and our work is funded by partner universities through commercial agreements signed directly between the company and each institution.', bodyAfter: 'Currently, the guidance, information, referral, and follow-up services provided to students and applicants are completely free. Make It Easy USA does not charge the student enrollment fees, application fees, follow-up fees, tuitions, commissions, or any other amount for the recruitment and guidance services it provides.<br/><br/>There is no direct contractual relationship between Make It Easy USA and the student. The student is a beneficiary of the guidance services offered by the company, in the context of their interest in entering academic programs of partner universities.<br/><br/>Make It Easy USA reserves the right, in the future, to offer optional complementary services for a fee (such as separate consulting, mentoring, or educational products). If this occurs, such services will always be clearly identified as paid and optional, with amounts, conditions, and scope informed transparently and in advance to the student, never being a condition for access to the free recruitment services described here.<br/><br/>Any charge made on behalf of Make It Easy USA outside the terms described here must be immediately reported to info@makeiteasyusa.com, as it may constitute attempted fraud.' },
      { title: '10. Payments to Third Parties', body: 'Amounts paid by the student to universities, SEVIS fees (I-901), consular fees (MRV), USCIS fees, expenses with sworn translation, proficiency exams, airfare, insurance, accommodation, and other expenses related to the process are the exclusive responsibility of the student and are not refundable by Make It Easy USA, regardless of the outcome of admission, visa, or status.', bodyAfter: 'Make It Easy USA does not intermediate, receive, process, or have any interference in these payments to third parties.' },
      { title: '11. Regulatory Changes', body: 'United States immigration laws and regulations may change at any time, without notice. Information that is accurate on the date of publication may become outdated. Make It Easy USA is not responsible for subsequent regulatory changes that affect the student\'s process, status, or benefits.' },
      { title: '12. Limitation of Liability', body: 'To the maximum extent permitted by applicable law, Make It Easy USA, its partners, employees, agents, and partners are not responsible for any direct, indirect, incidental, consequential damages, lost profits, or losses arising from decisions made based on the information provided, visa, CPT, OPT, or admission denials, loss of immigration status, or any other event related to the student\'s process.' },
      { title: '13. Acceptance of Terms', body: 'By using the services, information, materials, or communication channels of Make It Easy USA, participating in our events or orientations, or applying to academic programs through us, the student declares to have read, understood, and fully agreed to the terms of this Legal Disclaimer.', bodyAfter: 'If you have questions about this Legal Disclaimer, please contact: <a href="mailto:info@makeiteasyusa.com">info@makeiteasyusa.com</a>' },
    ],
  },
};

export default function TermosPage() {
  const { language } = useLanguage();
  const t = content[language];

  return (
    <main className={styles.page}>
      <div className={styles.container}>
        <h1 className={styles.title}>{t.title}</h1>
        <p className={styles.updated}>{t.updated}</p>
        {t.sections.map((s) => (
          <section key={s.title} className={styles.section}>
            <h2 className={styles.sectionTitle}>{s.title}</h2>
            <p dangerouslySetInnerHTML={{ __html: s.body }} />
            {s.list && (
              <ul className={styles.list}>
                {s.list.map((item) => <li key={item} dangerouslySetInnerHTML={{ __html: item }} />)}
              </ul>
            )}
            {s.bodyAfter && <p dangerouslySetInnerHTML={{ __html: s.bodyAfter }} />}
          </section>
        ))}
      </div>
    </main>
  );
}
